version: 2

updates:
  # Update npm packages
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 10

    # Group into shared PRs
    groups:
      build:
        patterns:
          - '*-loader'
          - '*-webpack-plugin'
          - '@babel/*'
          - 'autoprefixer'
          - 'babel-*'
          - 'core-js'
          - 'postcss'
          - 'postcss-*'
          - 'sass'
          - 'tsc-alias'
          - 'typescript'
          - 'webpack'
          - 'webpack-*'

      lint:
        patterns:
          - '@typescript-eslint/*'
          - 'editorconfig-checker'
          - 'eslint'
          - 'eslint-*'
          - 'husky'
          - 'lint-staged'
          - 'prettier'

      logging:
        patterns:
          - '*-pino'
          - '*-pino-format'
          - 'pino'
          - 'pino-*'

      tools:
        patterns:
          - 'cheerio'
          - 'concurrently'
          - 'jest'
          - 'nodemon'
          - 'tsx'

      types:
        patterns:
          - '@types/*'

    # Schedule run every Monday, local time
    schedule:
      interval: weekly
      time: '10:30'
      timezone: 'Europe/London'

    versioning-strategy: increase

    allow:
      # Include direct package.json updates
      - dependency-type: direct

  # Update GitHub Actions
  - package-ecosystem: github-actions
    directory: /

    # Schedule run every Monday, local time
    schedule:
      interval: weekly
      time: '10:30'
      timezone: 'Europe/London'
